sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
services:
  - postgresql

before_script:
  - createuser -U postgres test
  - createdb -U postgres -O test database
  - psql -d database -c "ALTER USER test PASSWORD 'test';"

env:
  - RUST_BACKTRACE=1

rust:
  - nightly

script:
  - cargo build
  - cargo test

matrix:
    include:
        - rust: stable
          script:
              - cargo build --manifest-path examples/todo-stable/Cargo.toml
        - rust: beta
          script:
              - cargo build --manifest-path examples/todo-stable/Cargo.toml
