[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["database"]
name = "tql_macros"
version = "0.1.0"

[dependencies]
rand = "^0.3.18"

[dependencies.proc-macro2]
version = "0.1"

[dependencies.quote]
git = "https://github.com/dtolnay/quote"

[dependencies.syn]
features = ["extra-traits", "printing", "full"]
git = "https://github.com/dtolnay/syn"
rev = "360efd23b84a4165de3d7f77b4132c80b74c60e9"

[lib]
proc-macro = true

[features]
unstable = ["proc-macro2/unstable"]
