[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["database"]
name = "tql_macros"
version = "0.1.0"

[dependencies]
literalext = "^0.1.1"
rand = "^0.3.18"

[dependencies.proc-macro2]
version = "0.1"

[dependencies.quote]
git = "https://github.com/dtolnay/quote"

[dependencies.syn]
features = ["extra-traits", "printing", "full"]
git = "https://github.com/dtolnay/syn"
rev = "22afd6d"

[lib]
proc-macro = true

[features]
unstable = ["proc-macro2/unstable"]
